### PR TITLE
Elastic Beanstalk

### PR DESCRIPTION
**Pull request by arokem**
A few small changes to allow us to run this on AWS. For example see: http://afq-viz.7wiywwd3xx.us-west-2.elasticbeanstalk.com

### CODE REVIEW

**Comment by arokem** [comment]
I'm not sure why 66bc81b got convolved into this PR, but it seems that it would not have any effect on the code. Attempts to rebase this out have resulted in much more complication and conflicts in that notebook file, so I tend not to push forward with the rebase. 

Otherwise, is this ready to go?

**Comment by richford** [comment]
Looks good to me. This will definitely help with having others test out the app. @arokem, can you show us "under the hood" at Wednesday's meeting? In any case, it looks ready to merge to me.

**Comment by arokem** [comment]
OK - I'll go ahead and merge this, and I'll show you all how this works on Wednesday (assuming I figure it out by then  😉 )

**Comment by arokem** [comment]
This is the documentation I am using to automate this: http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_nodejs_express.html

**Comment by arokem** [comment]
This also looks like a useful point of reference: https://github.com/awslabs/eb-node-express-sample

**Comment by arokem** [comment]
Master now deployed at: http://cirrus-afq.us-west-2.elasticbeanstalk.com

**Pull request merged**
