### PR TITLE
Auto-upload to github

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by arokem** [comment]
I believe this is ready for a review. Please take a look!

**Comment by jyeatman** [comment]
-Only the .nojekyll file is uploaded
-Prompted twice for pwd and usr name

**Comment by arokem** [comment]
The recent commit should fix the first of these points. I don't get the second of these, but I suspect that's because my terminal caches my github credentials.

**Comment by arokem** [comment]
Need to write documentation for this

**Comment by arokem** [comment]
This is ready to go, once someone has a chance to vet the documentation in the README file.

**Pull request merged**
