### PR TITLE
Disable arrow key panning in 3D orbit control.

### PR DESCRIPTION
**Pull request by richford**
Resolves issue #86

### CODE REVIEW

**Comment by richford** [comment]
Rebased onto master after acceptance of #89. This is just a one line addition PR.

**Comment by arokem** [comment]
I am curious: can you rebase this after the reorganization? I "git mv"ed the file in question, so I am wondering whether git knows how to follow it to its new location.

**Comment by richford** [comment]
I rebased locally onto pyapp. It worked. But I don't think I should push to this branch while this PR is open since this PR asks to merge into yeatmanlab:master. We want it to go into the pyapp branch, correct?

**Comment by richford** [comment]
Or perhaps we want it to go into both. Is there a reason we are keeping master and pyapp separate?

**Comment by arokem** [comment]
I've merged #95, so I was thinking of rebasing this on top of master. But
don't sweat it. Given it's a one-liner, a new PR with the change would also
be easy to get in.

**Comment by richford** [comment]
Sure thing. So I should submit a new PR to put this change on yeatmanlab:pyapp?

And going forward, should I be submitting PRs to yeatmanlab:pyapp or yeatmanlab:master?

**Comment by arokem** [comment]
The `pyapp` branch was merged into `master`, and it no longer exists. 

Please continue submitting PRs agains yeatmanlab:master

**Comment by richford** [comment]
Sorry if I'm being dense about this but I don't think it was merged into `yeatmanlab:master`. See, for example:
https://github.com/yeatmanlab/AFQ-Browser/tree/master
and
https://github.com/yeatmanlab/AFQ-Browser/tree/pyapp

**Comment by arokem** [comment]
Sorry - it was me being dense, and you're 100% right! I have no idea how
that happened.

See #97

**Comment by arokem** [comment]
Now you can rebase on master

**Comment by richford** [comment]
No worries. Thanks for merging. I'll rebase this.

**Comment by richford** [comment]
Rebased. I think this is ready to go.

**Pull request merged**
