### PR TITLE
WIP: reorganize global afqb object to allow saving state of browser.

### PR DESCRIPTION
**Pull request by richford**
Don't merge yet. Just creating the PR so that @anotherjoshsmith and I can work on this together.

### CODE REVIEW

**Comment by richford** [comment]
@anotherjoshsmith I just pushed another commit that actually saves and loads a settings.json file. We should complete the `afqb.global.saveSettings()` and `afqb.global.readSettings()` methods to include settings from the table and plots. Then we can go back through the table, plots, and three js files to remove any hard-coding of values.

**Comment by richford** [comment]
Addresses issue #47

**Comment by anotherjoshsmith** [comment]
Looks like you've got a good jump on this. I need to rework subject selection to add that to settings. Should I add settings for table and plots control boxes?

**Comment by richford** [comment]
How about this division of work:
#### Adam
- [x] Bundle selection
- [ ] Table settings (e.g. sortOn column, number of groups, etc.)

#### Josh
- [ ] Subject selection
- [ ] Plot settings (e.g. brush extents, zoom parameters, etc.)

The way I did it for the 3D settings was to have redundant data were the settings objects contain copies of the parameters in the `guiConfigObj` objects.

Does that work for you @anotherjoshsmith?

**Comment by richford** [comment]
@anotherjoshsmith Can you rebase this on top of the new master after #131? I tried but I'm running into some merge conflicts that you are probably more qualified to address since you authored #131.

**Comment by anotherjoshsmith** [comment]
@richford No problem, I'm on it!

**Comment by anotherjoshsmith** [comment]
@richford I've rebased my afqb-reorg branch on current master. If you checkout that branch it should be up-to-date. Not sure if working on my own afqb-reorg branch is the proper way to contribute to your branch with git. Let me know if there is a better way!

**Comment by richford** [comment]
@anotherjoshsmith I think you should be able to push directly to this PR. I checked the "allow edits from maintainers" box. @arokem is there a better way to do this? @jyeatman Did you make us all maintainers on this repo. I assume so because I can merge other PRs.

**Comment by richford** [comment]
Closing. Superseded by #139

**Pull request closed without merging**
