### PR TITLE
Allow user to select between equal size and equal interval for group splitting

### PR DESCRIPTION
**Pull request by richford**
Addresses issue #92. I think "equal interval" splitting only makes sense for quantitative values, correct? For ordinal values, it just defaults to the equal size method.

### CODE REVIEW

**Comment by jyeatman** [comment]
@richford it looks like the first interval is being computed from zero rather than the minimum value. For example in our example dataset, the youngest subject is 6 years of age.
https://yeatmanlab.github.io/AFQBrowser-demo/

Otherwise it looks great and works with the other PR I just merged

**Comment by richford** [comment]
Rebased after merging of #156. Thanks for pointing that out @jyeatman. I'll work on that.

**Comment by richford** [comment]
@jyeatman, the latest commit should fix that issue. I also added a commit that fixed a table formatting issue created after sorting columns.

**Comment by jyeatman** [comment]
@richford I'm not sure if this is new to this commit, but selecting rows of the table is broken. Subjects can only be selected through the tract details panels

**Pull request merged**
