### PR TITLE
Resolve selection in Safari

### PR DESCRIPTION
**Pull request by anotherjoshsmith**
Meant to resolve selection problem in safari. 
First commit fixes 1 line nodeKeys slicing issue.

### CODE REVIEW

**Comment by arokem** [comment]
Does this address #121? I only see commits that seem related to #119 (and that does indeed seem resolved here).

**Comment by anotherjoshsmith** [comment]
Only addresses #121 so far. Not sure how to fix the browser specific issue, I've primarily used chrome for development.

**Comment by jyeatman** [comment]
I'm fine if we don't support safari

**Comment by arokem** [comment]
Me too, except for the part where I am testing this on Safari all the time because Chrome keeps caching old states of the app :-)

**Comment by arokem** [comment]
Merging this for now. We can punt on Safari support until after 0.1...

**Comment by arokem** [comment]
Demo version is now running current master. Give it a spin! I think this might be 0.1 now?

**Pull request merged**
