### PR TITLE
start y-axis zoom/pan

### PR DESCRIPTION
**Pull request by anotherjoshsmith**
Zoom only applies to mean lines now.

### CODE REVIEW

**Comment by arokem** [comment]
- [x] Mean line is lost when zooming initially (but comes back if you sort)
- [x] Selection is lost when zooming. Zoomend is probably not doing the thing.

**Comment by anotherjoshsmith** [comment]
@arokem @jyeatman @richford I think this is ready to go. Feel free to play around with it and look for bugs before merging.

**Comment by richford** [comment]
I'm getting an issue where it draws the plot lines below the bottom axis when I zoom in far enough.

**Comment by anotherjoshsmith** [comment]
I plan on rolling that fix into a new branch aimed at #126 since it's an issue with how the plot is initially drawn

**Comment by richford** [comment]
Gotcha. In that case, this looks good to me.

**Comment by arokem** [comment]
LGTM as well. Merging!

**Pull request merged**
