### PR TITLE
Fix groups

### PR DESCRIPTION
**Pull request by richford**
This PR uses a d3 ordinal scale to assign bin indices to the sorted groups.

### CODE REVIEW

**Comment by richford** [comment]
I snuck in some formatting (indentation and camelCase) commits as well as a performance commit for updating the mean lines. There is one issue remaining on this PR: It is drawing a mean line for the null values in addition to the other groups. I'll push another commit once I have that fixed.

**Comment by jyeatman** [comment]
Just checked this PR with the data from email On Mon, Jan 30, 2017 at 1:25 PM

It seems like this has fixed the major issues. I can sort on floating point and strings

It seems to handle "null" mostly correctly. When there are nulls, and 2 groups are requested, a third mean line is draw for the nulls. But this is a minor issue. I think this is ready to merge

**Comment by jyeatman** [comment]
This fixed the null issue

While you are in this code, how hard is it to allow the binning to be done either by equal intervals (current) or equal group size? For example, adding a check box for equal group size in which case 2 groups on the age variable would have all the very young children (which there are many of) compared to all the adults. As oppose to now where the comparison will be <25 versus >25

**Comment by richford** [comment]
Just fixed the "null" group mean line plotting that @jyeatman pointed out. Here are two additional items that could be done along with a reason not to do them now:
- [ ] Fix sorting. Right now, the sort function is correctly sorting non-null values but the null values are sprinkled throughout the column. I think this fix should take place entirely in the `sort(a,b)` function in `sortable-table.js`.
- [ ] Speed up the plotting by reducing redundant line draws. Right now, in the `updatePlots()` function all of the lines in `tractData` are being redrawn every time we sort by a column. But everything except the mean lines should stay the same so a lot of redundant plotting is happening. This should only really be done when the user selects a different plot type (e.g. fa, md, etc). I suggest we separate the line drawing commands for the subject lines and for the mean lines. That way if the user is just sorting on a column, we don't have to redraw the subject lines. I started down this path by defining `updateAll` in `tract-details.js`. If `true`, then we should redraw all of the lines. If `false`, we only need to redraw the mean lines. But that's as far as I've gotten.

But, I don't think we should add any of those things to this PR. They are both beyond the scope of fixing the grouping and this PR is already bloated as is. I suggest we turn each of the points above into a separate issue and then address them in their own PRs.

**Comment by richford** [comment]
@jyeatman, it wouldn't be too hard I think. What we have now is equal group sizes. But we could easily allow the user to specify equal group sizes vs. a histogram with equal intervals. Like the above two things, I think we should make that a separate issue and not try to put it into this PR.

**Comment by jyeatman** [comment]
Agreed. I will merge this PR. If there were a way to dynamically adjust the grouping that would be incredibly useful. For example if you wanted to divide into 2 groups and then adjust the cutpoint for each group

**Pull request merged**
