### PR TITLE
Fix table sort

### PR DESCRIPTION
**Pull request by anotherjoshsmith**

### CODE REVIEW

**Comment by anotherjoshsmith** [comment]
Yes, good to go! Clears up issue #64. I can work through the conflicts now.

**Comment by arokem** [comment]
I just resolved conflicts through the web gui (!) I think we wanted the first to be like master (fixing table width stuff), and the second to be like your branch

**Comment by arokem** [comment]
Whoops. Looks like that put the table controller (the dat-gui thingee) in the top right corner of the page, for some reason. I'll try fixing it in a PR against this branch...

**Comment by arokem** [comment]
OK - I believe it's fixed on: https://github.com/anotherjoshsmith/AFQ-Browser/pull/1

**Comment by anotherjoshsmith** [comment]
Great! Just hopped on the bus, I'll check it out when I get home

**Comment by richford** [comment]
While testing this out, I found an error I made and have made a PR onto Josh's branch to fix it. In `3d-brain.js` I use `faPlotLength`, which is defined and set in `tract-details.js`. While testing with the large dataset, I realized that if `nodes.csv` takes a long time to read, the `3d-brain.js` portions of the code will be called before `faPlotLength` is set. I fixed it with a PR against this branch.

**Comment by arokem** [comment]
This is still rather slow on the 400 subject data-set, but otherwise seems to work. I suggest that we punt on that amount of data for now, and go ahead with this merge when it is ready to handle smaller amounts of data correctly.

**Comment by richford** [comment]
Agreed. LGTM.

**Comment by jyeatman** [comment]
I played around with this and it seems to work great. One minor aesthetic issue: When lines of the table are bolded the font renders a bit weird on my computer. Maybe we can turn of the bolding and just do the opacity change

**Comment by arokem** [comment]
Let's make these changes on a follow-up PR. 

Unless someone objects, I'll merge this late this afternoon.

**Comment by richford** [comment]
Agreed. We can even make those other issues part of the v0.1 milestone if we want but I this PR is good to go.

**Comment by jyeatman** [comment]
agreed

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Pull request merged**
