### PR TITLE
Add links to download data.

### PR DESCRIPTION
**Pull request by arokem**
TODO: 

- [x] Python script needs to create the `subjects.csv` file 
- [x] Buttons (are in #139, I believe)

### CODE REVIEW

**Comment by arokem** [comment]
Closes #133

**Comment by richford** [comment]
@arokem, the buttons in #139 only download the settings.json file (i.e. the browser based settings). Do you want a separate button to download the actual data?

**Comment by arokem** [comment]
No - that's what this PR is all about!

The issue I marked as a todo is that the buttons don't look good here. I assumed you added the definition of their graphics somewhere in #139 (in the css)? But I am actually not finding that right now. Am I doing something wrong here? I just don't see the nice oval around each one of the buttons. 

What do you think about their placement at the bottom of the bundle line plot panel?

**Comment by richford** [comment]
Ahh, I see. I misunderstood. For the buttons in #139, I had to include both the `<button>` tag and the `<label>` tag. Then I made the button invisible and adjusted the label's css. See https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/ for details. Really, the constraint for me was the `<file>` tag rather than the `<button>` tag.

**Comment by arokem** [comment]
All set here, I believe. Please give it a spin!

**Comment by arokem** [comment]
BTW -- most of the changes in the CSS are just changes to the line ending character -- nothing to worry about.

**Comment by jyeatman** [comment]
@richford is this PR ready to be checked and merged?

**Comment by arokem** [comment]
Ready on my end

**Comment by jyeatman** [comment]
checked - works as intended

**Comment by richford** [comment]
Oops sorry for the delayed response. Glad you merged it cause it looks good to me.

**Pull request merged**
