### PR TITLE
Rename 3d-brain.js to anatomy.js and add docstrings to afqb functions

### PR DESCRIPTION
**Pull request by richford**
This PR also moves all third-party js files into `js/third-party`.

### CODE REVIEW

**Comment by richford** [comment]
Will do `save-settings.js` documentation in a separate PR. I wanted to get this up here and merged quickly so that the file name changes don't disrupt other people's work too much.

**Comment by richford** [comment]
Nevermind. Just pushed up the save-settings docstrings as well.

**Comment by richford** [comment]
@anotherjoshsmith, did I format these correctly to integrate with your changes to sphinx?

**Comment by anotherjoshsmith** [comment]
@richford Looks like the only issue is how the list is rendered for afqb.three.init(). Here's how it looks now:

jsdoc-rendering

Adding an empty line after [line 183 in anatomy.js](https://github.com/yeatmanlab/AFQ-Browser/pull/226/commits/30b2490b29f93e4895ebee0743a1f2ef8194504b#diff-04dc8d66d3e6f5047f96470a7ac7b537R183) should fix this. I see the same issue for afqb.global.initSettings. Everything else looks good!

**Comment by richford** [comment]
Thanks @anotherjoshsmith. Good catch. Fixed.

**Comment by anotherjoshsmith** [comment]
Great, looks good! Merging now.

**Pull request merged**
