### PR TITLE
enh: added tract extent on brushing

### LINKED ISSUE #165: Display node numbers selected by brushable tracts
The numbers for the selected nodes should be displayed somewhere so that a user can conduct statistical analyses of these nodes outside of AFQ-Browser

### PR DESCRIPTION
**Pull request by akeshavan**
resolves #165

### CODE REVIEW

**Comment by arokem** [comment]
Two comments: 
- I would prefer a comma to a dash in between them (my brain sees this as a negative sign, and gets confused)
- I would cast to integer: I think that it's more accurate given that these are discrete nodes (does that make sense to you @jyeatman?)

**Comment by jyeatman** [comment]
Agreed - cast as integer

I'm fine with dash or comma

**Comment by akeshavan** [comment]
done - screen shot 2017-11-03 at 2 39 46 pm

**Comment by jyeatman** [comment]
Is this ready to be merged? If so I will test in a few cases and then merge if there are no issues

**Comment by richford** [comment]
LGTM

**Comment by arokem** [comment]
Oops. Sorry - I figured we were all in agreement, and then saw the "test in a few cases". I guess we can fix up later if needed :-/

**Comment by jyeatman** [comment]
All good

**Pull request merged**
