### PR TITLE
Change default brain orientation and adjust opacities

### PR DESCRIPTION
**Pull request by richford**
Addresses issue #35.

I also changed the default opacities of the left and right hemispheres and the grey fiber bundles. I thought these opacities gave a nice "first impression" but I'm not heavily invested in them so @arokem and @jyeatman if you feel the old opacities were more effective for researchers, just let me know.

### CODE REVIEW

**Comment by arokem** [comment]
This looks good to me (including changed opacities). I'll let others take a look before merging.

**Comment by jyeatman** [comment]
Is there a way to set the default lighting location as well? For me, the light looks like it is positioned behind the brain until I click somewhere and then it illuminates properly

**Comment by richford** [comment]
@jyeatman Good catch. Thanks. I just added a commit that sets the initial lighting to the camera position.

**Comment by jyeatman** [comment]
That looks much better! I messed around a bit with the opacity settings and
my vote is full opacity for the right hemi. Zero for the left hemi. And 0.2
for the fibers. But I don't feel strongly if others have a different
preference for the aesthetics

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Pull request merged**
