### PR TITLE
Binderfix

### PR DESCRIPTION
**Pull request by akeshavan**
* fixed the margins on the tooltip
* moved the binder button to the top w/ the official badge of binder
* disabled the button when on localhost

### CODE REVIEW

**Comment by akeshavan** [comment]
screenshot 2017-12-14 13 23 12

**Comment by arokem** [comment]
Looks great. Could we add a tooltip to this, such that when the button is grayed out, hovering over it brings up a text saying "deploy to Github to enable Binder integration"?

**Comment by arokem** [comment]
Better: "Publish to Github to enable Binder integration"

**Comment by akeshavan** [comment]
hows this:
screenshot 2017-12-14 13 41 20

**Comment by richford** [comment]
LGTM.

**Pull request merged**
