### PR TITLE
Afqb reorg

### PR DESCRIPTION
**Pull request by anotherjoshsmith**
Continue AFQB-reorg with rebase after #131.
Supercedes #135.

### CODE REVIEW

**Comment by richford** [comment]
How about this division of work:
#### Adam
- [x] Bundle selection
- [x] Table settings (e.g. sortOn column, number of groups, etc.)
- [x] Plot brushes
- [ ] Subject selection
- [ ] Plot zoom parameters

The way I did it for the 3D settings was to have redundant data were the settings objects contain copies of the parameters in the `guiConfigObj` objects.

**Comment by richford** [comment]
Make the title (e.g. AFQ Browser) part of the user settings.
- title
- subtitle
- title-url
- subtitle-url

**Comment by jyeatman** [comment]
@anotherjoshsmith @richford Is this PR a work in progress or should I go test and merge?

**Comment by richford** [comment]
Still a WIP. I'm very close though.

**Comment by jyeatman** [comment]
just noticed that my merge created conflicts here. Looks like a pretty simple rebase

**Comment by arokem** [comment]
OK - conflicts resolved. It was mostly just because I changed the line end markers in the css file in #140

**Comment by jyeatman** [comment]
Is this branch ready to be merged so that I can start creating saved browser states to match the manuscript figures?

**Comment by arokem** [comment]
I am interested in merging this ASAP, but I am unable to (quickly) resolve the conflicts here. These arose when we merged #145, I believe. @anotherjoshsmith : any chance you could take a look at the conflicts and resolve them? I believe you should be able to do this through the web interface, by clicking on the "resolve conflicts" button on this page. If you don't see such a button, please let me know, and we'll figure it out.

**Comment by anotherjoshsmith** [comment]
@arokem I've been traveling the last few days but return from China this weekend. I should be able to resolve the conflicts early next week.

**Comment by richford** [comment]
Okay, I just submitted #147. Apologies for the extra PR but the merge conflicts were horrible and once I was done it was easier to force push to my own branch and create a new PR. This is a lesson to me to keep my changes small rather than working on big monolithic changes all at once.

**Comment by richford** [comment]
Recommend closing this PR.

**Comment by arokem** [comment]
Superseded by #147

**Pull request closed without merging**
