### PR TITLE
Variable x axis

### PR DESCRIPTION
**Pull request by anotherjoshsmith**
This PR addresses #196. These changes should allow proper handling of TRACULA data with different numbers of nodes for each tract.

### CODE REVIEW

**Comment by anotherjoshsmith** [comment]
@arokem @richford @jyeatman @akeshavan There is a bit of redundant code that I should be able to turn into a couple of small functions, but wanted to get this out there in case anyone else wants to test the functionality before we meet.

**Comment by anotherjoshsmith** [comment]
Redundant code cleaned up with updates in ac0f1b3ccb6acbfcdf80b59f70197598f2d12cb4.

**Comment by richford** [comment]
@anotherjoshsmith The axes look good and brushing works for me. There are a few issues I noticed:

- [x] Brushing on core fibers doesn't cover the entire fiber. This is my fault from a previous PR. No need to address it here as #215 addresses it.
- [x] The `std` and `stderr` shading areas are displayed on top of some of the subject lines, preventing selection. As [described here](https://stackoverflow.com/a/17133220), can we put the shading areas in one `g` element and the lines in another `g` element and then render the areas first and then the lines.
- [x] Sorting on a column is not saved in the querystring for me. The weird thing is it works for the AFQ generated data but when I switch to the stuff in the `tracula_data` folder, then the grouping and sorting is not saved on a page refresh with the querystring.

**Comment by richford** [comment]
@anotherjoshsmith I created a PR against this branch on your fork to partially resolve the sorting issue. It's better but isn't completely fixed. The query string now saves an initial sort but if I click on a column twice, it won't save that on page refresh (weird). Again, this is all for the TRACULA generated data. Things work well for the AFQ generated data.

**Comment by richford** [comment]
@anotherjoshsmith I pushed another commit to that PR that fixes the restoration of column sorting from the querystring. If you merge that PR, I think all that's left is to fix the `std` area shading issue listed above.

**Comment by anotherjoshsmith** [comment]
@richford Great, thanks! I'll check out your changes and take care of the `std` area issue.

**Comment by anotherjoshsmith** [comment]
@richford Most recent commit fixes layering of g elements. Let me know if I broke anything!

**Comment by richford** [comment]
I found two errors, both of which are my fault I think. I submitted a PR on your branch to fix them. After that, I think it's good to go!

**Pull request merged**
