### PR TITLE
Redundant line draw

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by richford** [comment]
See #106 for complete history.

**Comment by arokem** [comment]
In it goes

**Comment by richford** [comment]
I'm fine with merging this. I'm still not sure we've addressed @jyeatman's issue with the single mean line on the left arcuate bundle. Perhaps after we merge this, we could open up a new issue for that (and mark it for the v0.2 milestone).

**Comment by arokem** [comment]
And with that, we've closed all the v0.1 milestone issues!

**Comment by jyeatman** [comment]
yeah, I'm fine with that. I have only noticed it for that single tract in
the example data

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by arokem** [comment]
FWIW: I don't think it's NaN's. I don't think there are NaN's in the
six-subject example data AFQ statistics.

**Pull request merged**
