### PR TITLE
Using afq_streamlines with tract key-names, instead of data_partial

### PR DESCRIPTION
**Pull request by arokem**
... that had integer keys. 

Towards using tract names as keys, instead of integers.

### CODE REVIEW

**Comment by richford** [comment]
LGTM.

**Comment by richford** [comment]
Also #185 goes a long way to using tract names as keys instead of integers as well. The only remaining integer keys are in 3d-brain.js. So whichever one gets merged first, we should check the other one to make sure it plays nicely.

**Comment by arokem** [comment]
Rebased on master. It works on my end!

I will keep going here, to add the AFQ ultra-tubes, so please don't merge yet.

**Comment by arokem** [comment]
OK: added `coreFiber` in each tract (which is the median of all the XYZ coordinates in each tract), and duplicated into a `streamlines.json` file from which the browser will read. Once we have that working, this file will get generated from the TRACULA data upon assembling from that.

**Comment by richford** [comment]
LGTM

**Pull request merged**
