### PR TITLE
Add a record to the afqvault manifest through a PR.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by arokem** [comment]
Still need to figure out how to create pull requests programmatically, but I believe that's the only remaining piece for this.

**Comment by arokem** [comment]
Still need to deduplicate if the row is already there.

**Comment by arokem** [comment]
OK - this is no longer WIP. I think it works as desired (@jyeatman : sorry for all those PR emails 😜)

**Comment by richford** [comment]
Not sure how to test this but since you and @akeshavan were working on this, if you say it's good to go, I'll believe you.

**Comment by richford** [comment]
Correct me if I'm wrong here:

Resolves #166 
Resolves #134

**Comment by arokem** [comment]
Should definitely resolve #166. We might want to leave #134 around, so that we can consider integration with something like Zenodo in the future, but I'd say we don't have to worry about that right now.

**Comment by arokem** [comment]
@akeshavan : could you please take a look and make sure that I am not doing something silly here.

**Comment by akeshavan** [comment]
looks good! merging

**Pull request merged**
