### PR TITLE
Adds an example notebook

### PR DESCRIPTION
**Pull request by arokem**
Uses sklearn on a data-set that is available online.

### CODE REVIEW

**Comment by jyeatman** [comment]
Is this different than the one in AFQ-Browser_data?

**Comment by arokem** [comment]
Nope. Same one, copied here as suggested over there (or in the manuscript? Did I understand correctly what you meant for us to do??)

**Comment by jyeatman** [comment]
Okay, I accepted the other one. And then, once the manuscript is submitted
for review, we can move all the data to research works and merge the code
from the AFQ-Browser_data into AFQ-Browser. Sound good?

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by arokem** [comment]
:+1:

**Pull request closed without merging**
